language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_install:
- pip install codecov
install:
- pip install .
script:
- coverage run tests/all_tests.py
after_success:
- coverage combine
- codecov
deploy:
  provider: pypi
  user: travis.rrze-hpc
  password:
    secure: Kwnx0lOmXJtmYQ2+ONRibTfsBN8aex6vqhmGI4z393i6/lvqZIBQ4/D4DXFXzw1RrE57Mv31X72FQ49huyECjRgGFsLM/+FT1qFPEUfm3kC3A+C6ui48QJ3kO8kz1EpOnD1iS3TvHmhicj/adUzsLvEUzcSEOj/rrElMeuwKVhvnaVWTaFuq7lH4abZ6fR3Q38e7RJjiVybxt8c/s7lvjJKSAr7/mrcEmLILO8tENGpa7QAN07Hcn397kwRQM812YVq+MbwqAfop7FSxjRRETGZg10y04R7cMIVwlOKpdB6fP4uCrEWivFdqFeGwAUC/duWN/x1k0hwStcFZ4QolfwDRr/eC5Bc1mFQvkzr1K8VqhCkOsPuGWtec1+yjpXrfEAxb5OLYGty+hRBWF5e8UWpjzJfbyqj0VYiFShH6SdR0X6F6wqVVowS6eutmxNFwzoYt7u7A1XM6jJ+mmuBB+pjQy9/Hl6lVojl/9uPixJV++cdn46jUPEaxSdAmfsbUWUPXCTKXH9lKMKDh2gUGR//zFQ3PlDyGJUN9lbcTrZxmCQun09wdM7M7KdHk1h0l3tomVwea4HPKCeVy5tFhU5aVS7HhYRt6DznK47AF6zc+mEQon7ZOX/lx3mXVzgLyM/BL9f4sH5BqnfOcmZv3Ick/5Rp61770j/hccozvz3A=
  skip_existing: true
  skip_cleanup: true
  on:
    repo: RRZE-HPC/pycachesim
    tag: true
